[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
libc = "0.2"
walkdir = "2.3"
crossterm = "0.22.1"
structopt = "0.3.21"